development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgres
  url: postgres://rktftqbzwnqvuc:Ei2J5iQI_-SL9eDpZHNrN-GeMi@ec2-23-21-165-183.compute-1.amazonaws.com:5432/d2pa4cmt899ofu
